### ISSUE TITLE
Integrate ailab-db package for document retrieval based on search queries

### ISSUE THREAD

**Issue by CFIALeronB** [ai-cfia/finesse-backend#1]
### Description
As part of our efforts to enhance the search functionality of our Flask backend, we need to integrate the AI-Lab DB package. This package will serve as our database/server to return relevant documents based on the search queries provided by the users.

### Requirements
- The AI-Lab DB package should be integrated in a way that it seamlessly interacts with the `/search` endpoint of our Flask application.
- The integration must handle the conversion of search queries into a format that AI-Lab DB can process.
- The search results returned by AI-Lab DB should be formatted into a JSON response that the frontend can use.
- Proper error handling should be in place to manage any issues that arise from the AI-Lab DB interaction.

### Dependencies
This task is dependent on the completion of another issue in the AI-Lab DB repository: [Create finesse-db python package for use by finesse-backend](https://github.com/ai-cfia/louis-db/issues/20). The progress and resolution of that issue will directly impact the implementation timeline for this feature.

### Endpoint Modification
The existing `/search` endpoint will be modified to use AI-Lab DB for querying documents:

```python
@app.route('/search', methods=['POST'])
def search():
    # Logic to interact with AI-Lab DB
    # ...
    return jsonify({"search_results": search_results})
```

### Testing

- Comprehensive unit tests must be written to ensure the interaction with AI-Lab DB works as expected.
- Integration tests should be carried out to confirm that the endpoint responds correctly to various search queries.

### Documentation

- Update the project's documentation to include details about the AI-Lab DB integration and any new setup/configuration required.

### Acceptance Criteria

- [ ] AI-Lab DB package is successfully integrated into the Flask project.
- [ ] The `/search` endpoint is able to return search results from AI-Lab DB.
- [ ] Unit and integration tests are passing.
- [ ] Documentation is updated.

**Comment by rngadam** [comment]
Note that @melanie-fressard and @JolanThomassin are working to rename louis-db ailab-db as well as providing a product specific python package finesse-db. Note that the issue you're pointing to is also already closed so you probably meant another issue.
