### ISSUE TITLE
Documentation Update in finesse-backend

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/finesse-backend#12]
Update `finesse-backend` documentation to accurately reflect recent system changes, new features, and any modified endpoints.

**Tasks:**
1. Review and identify outdated sections in the current documentation.
2. Add details about recent changes, new functionalities, and removed features.

**Acceptance Criteria:**
- [ ] Documentation aligns with the latest version of `finesse-backend`.

**Comment by rngadam** [comment]
We have a bit of a problem if we need to open separate issues for documentation. Documentation should be a task in each change (pull request). Refactoring and tests should also be part of the change. None of these should be a separate standalone issue. If our review process is not leading to good documentation being written with the actual change, we need to fix that deficiency and pay more careful attention to these tasks.

**Comment by k-allagbe** [comment]
> We have a bit of a problem if we need to open separate issues for documentation. Documentation should be a task in each change (pull request). Refactoring and tests should also be part of the change. None of these should be a separate standalone issue. If our review process is not leading to good documentation being written with the actual change, we need to fix that deficiency and pay more careful attention to these tasks.

Yes. I forgot to update it. Will make sure not to in the future.

**Comment by k-allagbe** [comment]
Will be done in #18.
