### ISSUE TITLE
Feature: Deploy finesse-backend on Azure with Terraform

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/finesse-backend#14]
Deploy finesse-backend on Azure

**Comment by rngadam** [comment]
In your issue, provide a deployment diagram and outline a plan of the work to do as a checklist:

* [ ] step 1
* [ ] step 2
* [ ] step 3 

Don't add extra labels on the title.

In your PR, have a more complete title "Terraform deployment of finesse-frontend"
