### ISSUE TITLE
Clean up llamaindex notebook to pass to DevOps team

### ISSUE THREAD

**Issue by leejaeka** [ai-cfia/finesse-backend#35]

**Comment by rngadam** [comment]
@leejaeka suggest that we do this in a separate repo (llamaindex-db) as your notebook will probably evolve into 

1) a Python library that we can integrate into finesse-backend as a python dependency and abstract queries to the LlamaIndex API
  Have a chat with @k-allagbe and @ibrahim-kabir on how that could look like
2) a set of infrastructure instructions for @ThomasCardin and @SonOfLope to deploy the service

**Comment by k-allagbe** [comment]
There is a single requirement from the finesse standpoint: a search method that returns a list of search results with a format similar to this: https://github.com/ai-cfia/finesse-data/blob/main/how%20to%20bring%20a%20cat%20to%20canada.json

Internally that function would use other functions that query the llama-index. I can create the repo and we'll work together on it.

**Comment by ibrahim-kabir** [comment]
llamaindex-db has been created, this issue is no longer relevant
